services:
  - type: web
    name: polly-voting
    env: elixir
    region: oregon
    plan: free
    buildCommand: mix deps.get --only prod && mix assets.deploy && mix phx.digest
    startCommand: mix phx.server
    envVars:
      - key: MIX_ENV
        value: prod
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        value: "ecto://localhost/polly_dev"
      - key: PHX_HOST
        sync: false
      - key: PORT
        value: 4000
